#!/usr/bin/env bash

set -o errexit
set -o nounset

export DATABASE_HOST="${DATABASE_HOST:-localhost}"
export DATABASE_PORT="${DATABASE_PORT:-5432}"
export DATABASE_USER="${DATABASE_USER:-postgres}"
export DATABASE_PASSWORD="${DATABASE_PASSWORD:-}"
export DATABASE_SCHEMAS="${DATABASE_SCHEMAS:-}"
export DATABASE_MIGRATIONS="${DATABASE_MIGRATIONS:-/flyway/sql}"
export DATABASE_NAME="${DATABASE_NAME:-${DATABASE_USER}}"
export DATABASE_URL="${DATABASE_URL:-jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}}"


fw() {
  local command="${1}"

  if [[ -z "${DATABASE_SCHEMAS}" ]]; then
    DATABASE_SCHEMAS_ARG=""
  else
    DATABASE_SCHEMAS_ARG="-schemas=${DATABASE_SCHEMAS}"
  fi

  # Shellcheck is wrong about the handling of the unquoted DATABASE_SCHEMAS_ARG
  # shellcheck disable=SC2086
  flyway \
    -X \
    -url="${DATABASE_URL}" \
    -user="${DATABASE_USER}" \
    -password="${DATABASE_PASSWORD}" \
    ${DATABASE_SCHEMAS_ARG} \
    -locations="filesystem:${DATABASE_MIGRATIONS}" \
    -table=schema_version \
    "${command}"
}

NUM_TRIES=0
MAX_TRIES=10
while [[ $NUM_TRIES -lt $MAX_TRIES ]]; do
  command="${1:-migrate}"
  if fw info; then
    fw $command
    exit $?
  else
    NUM_TRIES=$((NUM_TRIES + 1))
    sleep 2
  fi
done

echo "Could not run flyway info"
exit 1
